
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.DireitosUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IUsuarioLoginRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IUsuarioLoginGrupoRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IUsuarioGrupoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.ComboUnitOfWork.#ctor(Pragma.App.DAO.SysPragmaContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IConnectionsRepository})")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.FinanceUnitOfWork.#ctor(Pragma.App.DAO.InvestContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IIndiceRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IIndiceCotacaoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.LocalizationUnityOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IFeriadoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.PowerPointUnitOfWork.#ctor(Pragma.App.DAO.InvestContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptPaginaRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptPaginaImportadaRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptRelatorioInvestimentoRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptRelatorioPaginaRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptRelatorioRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IPptRotinaRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.SysUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IControleRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IAjudaSistemaRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IMenuRepository},System.Func{Pragma.DAO.Abstraction.IUnitOfWork,Pragma.App.DAO.Repositories.IParametrosRepository})")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.ComboUnitOfWork.#ctor(Pragma.App.DAO.SysPragmaContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IConnectionsRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.DireitosUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IUsuarioLoginRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IUsuarioLoginGrupoRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IUsuarioGrupoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.FinanceUnitOfWork.#ctor(Pragma.App.DAO.InvestContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IIndiceRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IIndiceCotacaoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.LocalizationUnityOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IFeriadoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.PowerPointUnitOfWork.#ctor(Pragma.App.DAO.InvestContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptPaginaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptPaginaImportadaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptRelatorioInvestimentoRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptRelatorioPaginaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptRelatorioRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IPptRotinaRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.SysUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IControleRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IAjudaSistemaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IMenuRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IParametrosRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.GalgoUnitOfWork.#ctor(Pragma.App.DAO.InvestContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IGalgoRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IGalgoLogRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.LocalizationUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IFeriadoRepository})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0031:Check for null before calling a delegate", Justification = "<Pending>", Scope = "member", Target = "~M:Pragma.App.DAO.SysUnitOfWork.#ctor(Pragma.App.DAO.SysContext,System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IControleRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IAjudaSistemaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IMenuSistemaRepository},System.Func{Pragma.DAO.Abstraction.IContext,Pragma.App.DAO.Repositories.IParametrosRepository})")]